#!/bin/bash
#SBATCH --partition=gpu4_medium,gpu4_dev
#SBATCH --job-name=LDMBth9
#SBATCH --mem-per-cpu=3G
#SBATCH --time=04:00:00
#SBATCH --tasks=1
#SBATCH --cpus-per-task=40
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:4
srun /gpfs/data/glimcherlab/BoShen/LDDM/Fit/batchLDDM

