#!/bin/bash
#SBATCH --partition=gpu8_medium
#SBATCH --job-name=LDM7VII
#SBATCH --mem-per-cpu=3G
#SBATCH --time=3-00:00:00
#SBATCH --tasks=1
#SBATCH --cpus-per-task=20
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:8
srun /gpfs/data/glimcherlab/BoShen/RecurrentModel/Fit/batch7pars

