#!/bin/bash
#SBATCH --partition=gpu8_medium
#SBATCH --job-name=ABS
#SBATCH --mem-per-cpu=3G
#SBATCH --time=2-12:00:00
#SBATCH --tasks=1
#SBATCH --cpus-per-task=20
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:4
srun /gpfs/data/glimcherlab/BoShen/LDDM/IIA/batchIIAABS

